# Generated by Django 5.2.17 on 2026-08-12 21:33

import configuracion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_institucion",
                    models.CharField(
                        max_length=200, verbose_name="nombre de la institución"
                    ),
                ),
                (
                    "nombre_corto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nombre corto"
                    ),
                ),
                (
                    "siglas",
                    models.CharField(blank=True, max_length=30, verbose_name="siglas"),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="eslogan"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "logo_primario",
                    models.ImageField(
                        blank=True,
                        upload_to=configuracion.models.ruta_identidad,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif"]
                            ),
                            configuracion.models.validar_tamano_imagen,
                        ],
                        verbose_name="logo primario",
                    ),
                ),
                (
                    "logo_secundario",
                    models.ImageField(
                        blank=True,
                        upload_to=configuracion.models.ruta_identidad,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif"]
                            ),
                            configuracion.models.validar_tamano_imagen,
                        ],
                        verbose_name="logo secundario",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        upload_to=configuracion.models.ruta_identidad,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif"]
                            ),
                            configuracion.models.validar_tamano_imagen,
                        ],
                        verbose_name="favicon",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "telefono_secundario",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono secundario"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="sitio web")),
                (
                    "nit",
                    models.CharField(blank=True, max_length=50, verbose_name="NIT"),
                ),
                (
                    "horario_atencion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="horario de atención"
                    ),
                ),
                (
                    "nombre_sistema",
                    models.CharField(
                        default="Sistema base",
                        max_length=150,
                        verbose_name="nombre del sistema",
                    ),
                ),
                (
                    "version_sistema",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="versión del sistema"
                    ),
                ),
                (
                    "texto_pie_pagina",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="texto del pie de página",
                    ),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#006666",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Ingrese un color hexadecimal válido, por ejemplo #006666.",
                            )
                        ],
                        verbose_name="color primario",
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#FF6150",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Ingrese un color hexadecimal válido, por ejemplo #006666.",
                            )
                        ],
                        verbose_name="color secundario",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuraciones_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración del sistema",
                "verbose_name_plural": "configuración del sistema",
            },
        ),
    ]
